name = "dl"
main = "cloudflare/worker.js"
compatibility_date = "2024-04-05"

[vars]
BACKEND_ORIGIN = "https://saahiyo-stream-bot.hf.space"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
